### ISSUE TITLE
Add an animated background

### ISSUE THREAD

**Issue by JohannesNicholas** [UTAS-Programming-Club/UTAS-Programming-Club.github.io#1]
An animated background to the page could add a nice feel and wow factor. Could be done with javascript and a canvas or with html and CSS. It shouldn't be too distracting either, maybe a moving and color changing gradient could work?

**Comment by mk-sdev** [comment]
I made something. You can choose other colors if you want.

**Comment by JohannesNicholas** [comment]
Thank you @mkaletaa
Looks great, merged in https://github.com/UTAS-Programming-Club/UTAS-Programming-Club.github.io/pull/7
:)
